services:
  - type: web
    name: yt-music-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
